version: '3'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: users_database
      MYSQL_ROOT_PASSWORD: test_password
    networks:
      - app-network

  backend:
    image: ${ECR_REGISTRY}/backend:${BACKEND_TAG}
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: test_password
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - app-network

  frontend:
    image: ${ECR_REGISTRY}/frontend:${FRONTEND_TAG}
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge