services:
  backend:
    image: 821625964871.dkr.ecr.us-east-1.amazonaws.com/backend:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: angularspring-db.cixgnehzwu0c.us-east-1.rds.amazonaws.com
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: 3306
      MYSQL_DATABASE: users_database
      SPRING_PROFILES_ACTIVE: test
    networks:
      - app-network

  frontend:
    image: 821625964871.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge