name: Smoke Test Deployment

on:
#  push:
#    branches:
#      - main
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      backend_tag:
        description: 'Backend image tag'
        required: true
      frontend_tag:
        description: 'Frontend image tag'
        required: true

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy_test:
#    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Set Image Tags
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "BACKEND_TAG=${{ github.event.client_payload.backend_tag }}" >> $GITHUB_ENV
            echo "FRONTEND_TAG=${{ github.event.client_payload.frontend_tag }}" >> $GITHUB_ENV
          else
            echo "BACKEND_TAG=${{ github.event.inputs.backend_tag }}" >> $GITHUB_ENV
            echo "FRONTEND_TAG=${{ github.event.inputs.frontend_tag }}" >> $GITHUB_ENV
          fi

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem

      - name: Launch Test EC2 Instance
        id: launch-ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-05b10e08d247fb927 \
            --instance-type t2.micro \
            --key-name ${{ secrets.EC2_KEY_NAME }} \
            --security-group-ids ${{ secrets.TEST_SG_ID }} \
            --subnet-id ${{ secrets.PUBLIC_SUBNET_ID }} \
            --associate-public-ip-address \
            --user-data file://config/test-ec2-userdata.sh \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=TestInstance}]" \
            --query 'Instances[0].InstanceId' \
            --output text)
          
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          
          echo "Waiting for EC2 instance to be ready..."
          sleep 30
          
          # Get public IP
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          
          # Debug output
          echo "The EC2 instance ID is: $INSTANCE_ID"
          echo "The EC2 instance public IP is: $PUBLIC_IP"

      - name: Deploy and Test
        id: deploy-test
        run: |
          # Debug IP address
          echo "Connecting to EC2 at IP: ${{ env.PUBLIC_IP }}"
          # Copy scripts and config to EC2
          scp -i ~/.ssh/ec2-key.pem -o StrictHostKeyChecking=no \
            scripts/setup-docker.sh \
            scripts/ecr-login.sh \
            scripts/run-tests.sh \
            templates/docker-compose.test.yml \
            ec2-user@${{ env.PUBLIC_IP }}:~/
          
          # Run setup and tests
          ssh -i ~/.ssh/ec2-key.pem -o StrictHostKeyChecking=no ec2-user@${{ env.PUBLIC_IP }} << EOF
            # Setup environment variables
            export ECR_REGISTRY=$ECR_REGISTRY
            export BACKEND_TAG=$BACKEND_TAG
            export FRONTEND_TAG=$FRONTEND_TAG
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          
            # Install Docker
            chmod +x setup-docker.sh
            sudo ./setup-docker.sh
          
            # Log into ECR
            chmod +x ecr-login.sh
            sudo -E ./ecr-login.sh $AWS_REGION
          
            # Start containers
            mv docker-compose.test.yml docker-compose.yml
            sudo -E docker-compose up -d
          
            # Run tests
            chmod +x run-tests.sh
            sudo -E ./run-tests.sh
            exit \$?
          EOF
          
          # Store test result
          TEST_RESULT=$?
          echo "TEST_RESULT=$TEST_RESULT" >> $GITHUB_ENV

      - name: Process Test Results
        run: |
          if [ "${{ env.test_result }}" == "0" ]; then
            # Tests passed, tag images as QA-ready
            chmod +x scripts/tag-images.sh
            ./scripts/tag-images.sh $BACKEND_TAG $FRONTEND_TAG
            echo "Tests passed, images tagged as QA-ready"
          else
            # Tests failed, remove images
            chmod +x scripts/remove-images.sh
            ./scripts/remove-images.sh $BACKEND_TAG $FRONTEND_TAG
            echo "Tests failed, images removed from ECR"
            exit 1
          fi

      - name: Cleanup EC2 Instance
        if: always()
        run: |
          aws ec2 terminate-instances --instance-ids ${{ env.instance_id }}
          echo "Test EC2 instance terminated"